using System.Collections.Generic;
using UnityEngine;

namespace Dpr.Message
{
    public static class MessageFontDataConstants
    {
        public static readonly Dictionary<int, MessageFontTagData> TEXT_FONT_TABLE = new Dictionary<int, MessageFontTagData>()
        {
            { 1,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Std,   languageId = MessageEnumData.MsgLangId.JPN, fontFileIndex = 0 } },
            { 2,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Small, languageId = MessageEnumData.MsgLangId.JPN, fontFileIndex = 0 } },
            { 3,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Big,   languageId = MessageEnumData.MsgLangId.JPN, fontFileIndex = 0 } },
            { 4,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Std,   languageId = MessageEnumData.MsgLangId.USA, fontFileIndex = 1 } },
            { 5,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Small, languageId = MessageEnumData.MsgLangId.USA, fontFileIndex = 1 } },
            { 6,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Big,   languageId = MessageEnumData.MsgLangId.USA, fontFileIndex = 1 } },
            { 7,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Std,   languageId = MessageEnumData.MsgLangId.KOR, fontFileIndex = 2 } },
            { 8,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Small, languageId = MessageEnumData.MsgLangId.KOR, fontFileIndex = 2 } },
            { 9,  new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Big,   languageId = MessageEnumData.MsgLangId.KOR, fontFileIndex = 2 } },
            { 10, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Std,   languageId = MessageEnumData.MsgLangId.SCH, fontFileIndex = 3 } },
            { 11, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Small, languageId = MessageEnumData.MsgLangId.SCH, fontFileIndex = 3 } },
            { 12, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Big,   languageId = MessageEnumData.MsgLangId.SCH, fontFileIndex = 3 } },
            { 13, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Std,   languageId = MessageEnumData.MsgLangId.TCH, fontFileIndex = 4 } },
            { 14, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Small, languageId = MessageEnumData.MsgLangId.TCH, fontFileIndex = 4 } },
            { 15, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Big,   languageId = MessageEnumData.MsgLangId.TCH, fontFileIndex = 4 } },
            { 16, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Huge,  languageId = MessageEnumData.MsgLangId.JPN, fontFileIndex = 0 } },
            { 17, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Huge,  languageId = MessageEnumData.MsgLangId.USA, fontFileIndex = 1 } },
            { 18, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Huge,  languageId = MessageEnumData.MsgLangId.KOR, fontFileIndex = 2 } },
            { 19, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Huge,  languageId = MessageEnumData.MsgLangId.SCH, fontFileIndex = 3 } },
            { 20, new MessageFontTagData() { fontSizeId = MessageEnumData.FontSizeID.Huge,  languageId = MessageEnumData.MsgLangId.TCH, fontFileIndex = 4 } },
        };
        public static readonly Dictionary<int, int> FONT_FILE_TABLE = new Dictionary<int, int>()
        {
            { (int)MessageEnumData.MsgLangId.JPN, 0 },
            { (int)MessageEnumData.MsgLangId.USA, 1 },
            { (int)MessageEnumData.MsgLangId.FRA, 1 },
            { (int)MessageEnumData.MsgLangId.ITA, 1 },
            { (int)MessageEnumData.MsgLangId.DEU, 1 },
            { (int)MessageEnumData.MsgLangId.ESP, 1 },
            { (int)MessageEnumData.MsgLangId.KOR, 2 },
            { (int)MessageEnumData.MsgLangId.SCH, 3 },
            { (int)MessageEnumData.MsgLangId.TCH, 4 },
        };
        public static readonly string[] FONT_FILE_NAME_ARRAY = new string[5]
        {
            "jpn_font", "efigs_font", "kor_font", "sch_font", "tch_font",
        };
        public static readonly Dictionary<int, MessageStyleData> FONT_STYLE_DATA_TABLE = new Dictionary<int, MessageStyleData>()
        {
            { 0,   new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 1,   new MessageStyleData() { strNum = 0x17, fontSizeId = 2 } },
            { 2,   new MessageStyleData() { strNum = 0x1C, fontSizeId = 2 } },
            { 3,   new MessageStyleData() { strNum = 0x01, fontSizeId = 2 } },
            { 4,   new MessageStyleData() { strNum = 0x04, fontSizeId = 2 } },
            { 5,   new MessageStyleData() { strNum = 0x06, fontSizeId = 2 } },
            { 6,   new MessageStyleData() { strNum = 0x07, fontSizeId = 2 } },
            { 7,   new MessageStyleData() { strNum = 0x08, fontSizeId = 2 } },
            { 8,   new MessageStyleData() { strNum = 0x0A, fontSizeId = 2 } },
            { 9,   new MessageStyleData() { strNum = 0x0A, fontSizeId = 2 } },
            { 10,  new MessageStyleData() { strNum = 0x0B, fontSizeId = 2 } },
            { 11,  new MessageStyleData() { strNum = 0x0B, fontSizeId = 2 } },
            { 12,  new MessageStyleData() { strNum = 0x0C, fontSizeId = 2 } },
            { 13,  new MessageStyleData() { strNum = 0x0C, fontSizeId = 2 } },
            { 14,  new MessageStyleData() { strNum = 0x0E, fontSizeId = 2 } },
            { 15,  new MessageStyleData() { strNum = 0x0F, fontSizeId = 2 } },
            { 16,  new MessageStyleData() { strNum = 0x0F, fontSizeId = 2 } },
            { 17,  new MessageStyleData() { strNum = 0x10, fontSizeId = 2 } },
            { 18,  new MessageStyleData() { strNum = 0x11, fontSizeId = 2 } },
            { 19,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 20,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 21,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 22,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 23,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 24,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 25,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 26,  new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 27,  new MessageStyleData() { strNum = 0x14, fontSizeId = 2 } },
            { 28,  new MessageStyleData() { strNum = 0x17, fontSizeId = 2 } },
            { 29,  new MessageStyleData() { strNum = 0x17, fontSizeId = 2 } },
            { 30,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 31,  new MessageStyleData() { strNum = 0x17, fontSizeId = 1 } },
            { 32,  new MessageStyleData() { strNum = 0x01, fontSizeId = 1 } },
            { 33,  new MessageStyleData() { strNum = 0x02, fontSizeId = 1 } },
            { 34,  new MessageStyleData() { strNum = 0x03, fontSizeId = 1 } },
            { 35,  new MessageStyleData() { strNum = 0x04, fontSizeId = 1 } },
            { 36,  new MessageStyleData() { strNum = 0x05, fontSizeId = 1 } },
            { 37,  new MessageStyleData() { strNum = 0x06, fontSizeId = 1 } },
            { 38,  new MessageStyleData() { strNum = 0x07, fontSizeId = 1 } },
            { 39,  new MessageStyleData() { strNum = 0x08, fontSizeId = 1 } },
            { 40,  new MessageStyleData() { strNum = 0x08, fontSizeId = 1 } },
            { 41,  new MessageStyleData() { strNum = 0x09, fontSizeId = 1 } },
            { 42,  new MessageStyleData() { strNum = 0x0A, fontSizeId = 1 } },
            { 43,  new MessageStyleData() { strNum = 0x0A, fontSizeId = 1 } },
            { 44,  new MessageStyleData() { strNum = 0x0B, fontSizeId = 1 } },
            { 45,  new MessageStyleData() { strNum = 0x0B, fontSizeId = 1 } },
            { 46,  new MessageStyleData() { strNum = 0x0C, fontSizeId = 1 } },
            { 47,  new MessageStyleData() { strNum = 0x0D, fontSizeId = 1 } },
            { 48,  new MessageStyleData() { strNum = 0x0E, fontSizeId = 1 } },
            { 49,  new MessageStyleData() { strNum = 0x0F, fontSizeId = 1 } },
            { 50,  new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 51,  new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 52,  new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 53,  new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 54,  new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 55,  new MessageStyleData() { strNum = 0x11, fontSizeId = 1 } },
            { 56,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 57,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 58,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 59,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 60,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 61,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 62,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 63,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 64,  new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 65,  new MessageStyleData() { strNum = 0x14, fontSizeId = 1 } },
            { 66,  new MessageStyleData() { strNum = 0x14, fontSizeId = 1 } },
            { 67,  new MessageStyleData() { strNum = 0x14, fontSizeId = 1 } },
            { 68,  new MessageStyleData() { strNum = 0x15, fontSizeId = 1 } },
            { 69,  new MessageStyleData() { strNum = 0x15, fontSizeId = 1 } },
            { 70,  new MessageStyleData() { strNum = 0x16, fontSizeId = 1 } },
            { 71,  new MessageStyleData() { strNum = 0x17, fontSizeId = 1 } },
            { 72,  new MessageStyleData() { strNum = 0x17, fontSizeId = 1 } },
            { 73,  new MessageStyleData() { strNum = 0x18, fontSizeId = 1 } },
            { 74,  new MessageStyleData() { strNum = 0x1E, fontSizeId = 1 } },
            { 75,  new MessageStyleData() { strNum = 0x2B, fontSizeId = 1 } },
            { 76,  new MessageStyleData() { strNum = 0x01, fontSizeId = 0 } },
            { 77,  new MessageStyleData() { strNum = 0x02, fontSizeId = 0 } },
            { 78,  new MessageStyleData() { strNum = 0x03, fontSizeId = 0 } },
            { 79,  new MessageStyleData() { strNum = 0x04, fontSizeId = 0 } },
            { 80,  new MessageStyleData() { strNum = 0x05, fontSizeId = 0 } },
            { 81,  new MessageStyleData() { strNum = 0x06, fontSizeId = 0 } },
            { 82,  new MessageStyleData() { strNum = 0x07, fontSizeId = 0 } },
            { 83,  new MessageStyleData() { strNum = 0x08, fontSizeId = 0 } },
            { 84,  new MessageStyleData() { strNum = 0x08, fontSizeId = 0 } },
            { 85,  new MessageStyleData() { strNum = 0x08, fontSizeId = 0 } },
            { 86,  new MessageStyleData() { strNum = 0x09, fontSizeId = 0 } },
            { 87,  new MessageStyleData() { strNum = 0x0A, fontSizeId = 0 } },
            { 88,  new MessageStyleData() { strNum = 0x0A, fontSizeId = 0 } },
            { 89,  new MessageStyleData() { strNum = 0x0A, fontSizeId = 0 } },
            { 90,  new MessageStyleData() { strNum = 0x0B, fontSizeId = 0 } },
            { 91,  new MessageStyleData() { strNum = 0x0C, fontSizeId = 0 } },
            { 92,  new MessageStyleData() { strNum = 0x0D, fontSizeId = 0 } },
            { 93,  new MessageStyleData() { strNum = 0x0E, fontSizeId = 0 } },
            { 94,  new MessageStyleData() { strNum = 0x0F, fontSizeId = 0 } },
            { 95,  new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 96,  new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 97,  new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 98,  new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 99,  new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 100, new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 101, new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 102, new MessageStyleData() { strNum = 0x12, fontSizeId = 0 } },
            { 103, new MessageStyleData() { strNum = 0x12, fontSizeId = 0 } },
            { 104, new MessageStyleData() { strNum = 0x12, fontSizeId = 0 } },
            { 105, new MessageStyleData() { strNum = 0x12, fontSizeId = 0 } },
            { 106, new MessageStyleData() { strNum = 0x14, fontSizeId = 0 } },
            { 107, new MessageStyleData() { strNum = 0x14, fontSizeId = 0 } },
            { 108, new MessageStyleData() { strNum = 0x15, fontSizeId = 0 } },
            { 109, new MessageStyleData() { strNum = 0x15, fontSizeId = 0 } },
            { 110, new MessageStyleData() { strNum = 0x16, fontSizeId = 0 } },
            { 111, new MessageStyleData() { strNum = 0x16, fontSizeId = 0 } },
            { 112, new MessageStyleData() { strNum = 0x17, fontSizeId = 0 } },
            { 113, new MessageStyleData() { strNum = 0x17, fontSizeId = 0 } },
            { 114, new MessageStyleData() { strNum = 0x17, fontSizeId = 0 } },
            { 115, new MessageStyleData() { strNum = 0x20, fontSizeId = 0 } },
            { 116, new MessageStyleData() { strNum = 0x2E, fontSizeId = 0 } },
            { 117, new MessageStyleData() { strNum = 0x0A, fontSizeId = 2 } },
            { 118, new MessageStyleData() { strNum = 0x0E, fontSizeId = 2 } },
            { 119, new MessageStyleData() { strNum = 0x05, fontSizeId = 1 } },
            { 120, new MessageStyleData() { strNum = 0x06, fontSizeId = 1 } },
            { 121, new MessageStyleData() { strNum = 0x08, fontSizeId = 1 } },
            { 122, new MessageStyleData() { strNum = 0x08, fontSizeId = 1 } },
            { 123, new MessageStyleData() { strNum = 0x08, fontSizeId = 1 } },
            { 124, new MessageStyleData() { strNum = 0x09, fontSizeId = 1 } },
            { 125, new MessageStyleData() { strNum = 0x0A, fontSizeId = 1 } },
            { 126, new MessageStyleData() { strNum = 0x0A, fontSizeId = 1 } },
            { 127, new MessageStyleData() { strNum = 0x0A, fontSizeId = 1 } },
            { 128, new MessageStyleData() { strNum = 0x0C, fontSizeId = 1 } },
            { 129, new MessageStyleData() { strNum = 0x0C, fontSizeId = 1 } },
            { 130, new MessageStyleData() { strNum = 0x0C, fontSizeId = 1 } },
            { 131, new MessageStyleData() { strNum = 0x0E, fontSizeId = 1 } },
            { 132, new MessageStyleData() { strNum = 0x0F, fontSizeId = 1 } },
            { 133, new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 134, new MessageStyleData() { strNum = 0x05, fontSizeId = 0 } },
            { 135, new MessageStyleData() { strNum = 0x06, fontSizeId = 0 } },
            { 136, new MessageStyleData() { strNum = 0x08, fontSizeId = 0 } },
            { 137, new MessageStyleData() { strNum = 0x08, fontSizeId = 0 } },
            { 138, new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 139, new MessageStyleData() { strNum = 0x0E, fontSizeId = 0 } },
            { 140, new MessageStyleData() { strNum = 0x01, fontSizeId = 2 } },
            { 141, new MessageStyleData() { strNum = 0x02, fontSizeId = 2 } },
            { 142, new MessageStyleData() { strNum = 0x03, fontSizeId = 2 } },
            { 143, new MessageStyleData() { strNum = 0x04, fontSizeId = 2 } },
            { 144, new MessageStyleData() { strNum = 0x05, fontSizeId = 2 } },
            { 145, new MessageStyleData() { strNum = 0x06, fontSizeId = 2 } },
            { 146, new MessageStyleData() { strNum = 0x01, fontSizeId = 1 } },
            { 147, new MessageStyleData() { strNum = 0x02, fontSizeId = 1 } },
            { 148, new MessageStyleData() { strNum = 0x03, fontSizeId = 1 } },
            { 149, new MessageStyleData() { strNum = 0x04, fontSizeId = 1 } },
            { 150, new MessageStyleData() { strNum = 0x05, fontSizeId = 1 } },
            { 151, new MessageStyleData() { strNum = 0x06, fontSizeId = 1 } },
            { 152, new MessageStyleData() { strNum = 0x07, fontSizeId = 1 } },
            { 153, new MessageStyleData() { strNum = 0x08, fontSizeId = 1 } },
            { 154, new MessageStyleData() { strNum = 0x09, fontSizeId = 1 } },
            { 155, new MessageStyleData() { strNum = 0x0A, fontSizeId = 1 } },
            { 156, new MessageStyleData() { strNum = 0x0B, fontSizeId = 1 } },
            { 157, new MessageStyleData() { strNum = 0x0C, fontSizeId = 1 } },
            { 158, new MessageStyleData() { strNum = 0x0E, fontSizeId = 1 } },
            { 159, new MessageStyleData() { strNum = 0x10, fontSizeId = 1 } },
            { 160, new MessageStyleData() { strNum = 0x11, fontSizeId = 1 } },
            { 161, new MessageStyleData() { strNum = 0x12, fontSizeId = 1 } },
            { 162, new MessageStyleData() { strNum = 0x13, fontSizeId = 1 } },
            { 163, new MessageStyleData() { strNum = 0x18, fontSizeId = 1 } },
            { 164, new MessageStyleData() { strNum = 0x01, fontSizeId = 0 } },
            { 165, new MessageStyleData() { strNum = 0x02, fontSizeId = 0 } },
            { 166, new MessageStyleData() { strNum = 0x03, fontSizeId = 0 } },
            { 167, new MessageStyleData() { strNum = 0x04, fontSizeId = 0 } },
            { 168, new MessageStyleData() { strNum = 0x05, fontSizeId = 0 } },
            { 169, new MessageStyleData() { strNum = 0x06, fontSizeId = 0 } },
            { 170, new MessageStyleData() { strNum = 0x07, fontSizeId = 0 } },
            { 171, new MessageStyleData() { strNum = 0x08, fontSizeId = 0 } },
            { 172, new MessageStyleData() { strNum = 0x09, fontSizeId = 0 } },
            { 173, new MessageStyleData() { strNum = 0x0A, fontSizeId = 0 } },
            { 174, new MessageStyleData() { strNum = 0x0B, fontSizeId = 0 } },
            { 175, new MessageStyleData() { strNum = 0x0C, fontSizeId = 0 } },
            { 176, new MessageStyleData() { strNum = 0x0E, fontSizeId = 0 } },
            { 177, new MessageStyleData() { strNum = 0x10, fontSizeId = 0 } },
            { 178, new MessageStyleData() { strNum = 0x11, fontSizeId = 0 } },
            { 179, new MessageStyleData() { strNum = 0x13, fontSizeId = 0 } },
            { 180, new MessageStyleData() { strNum = 0x18, fontSizeId = 0 } },
            { 181, new MessageStyleData() { strNum = 0x06, fontSizeId = 3 } },
            { 182, new MessageStyleData() { strNum = 0x0A, fontSizeId = 3 } },
            { 183, new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 184, new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 185, new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 186, new MessageStyleData() { strNum = 0x12, fontSizeId = 2 } },
            { 187, new MessageStyleData() { strNum = 0x0E, fontSizeId = 2 } },
        };
        public static readonly Dictionary<int, int> FONT_SIZE_TABLE = new Dictionary<int, int>()
        {
            { 0, 32 },
            { 1, 42 },
            { 2, 54 },
            { 3, 116 },
        };
        public static readonly Color DEFAULT_FONT_COLOR = new Color(1.0f, 1.0f, 1.0f, 1.0f);
        public static readonly Color NETWORK_TEXT_COLOR = new Color(245.0f, 245.0f, 245.0f, 255.0f);
        public static readonly MessageStyleColorData[] FONT_COLOR_ARRAY = new MessageStyleColorData[15]
        {
            new MessageStyleColorData(0.0f,   0.0f,   0.0f,   255.0f),
            new MessageStyleColorData(240.0f, 30.0f,  30.0f,  255.0f),
            new MessageStyleColorData(0.0f,   100.0f, 255.0f, 255.0f),
            new MessageStyleColorData(0.0f,   150.0f, 90.0f,  255.0f),
            new MessageStyleColorData(240.0f, 70.0f,  240.0f, 255.0f),
            new MessageStyleColorData(255.0f, 255.0f, 70.0f,  255.0f),
            new MessageStyleColorData(255.0f, 80.0f,  0.0f,   255.0f),
            new MessageStyleColorData(140.0f, 0.0f,   255.0f, 255.0f),
            new MessageStyleColorData(80.0f,  200.0f, 230.0f, 255.0f),
            new MessageStyleColorData(0.0f,   80.0f,  190.0f, 255.0f),
            new MessageStyleColorData(244.0f, 244.0f, 244.0f, 255.0f),
            new MessageStyleColorData(183.0f, 183.0f, 183.0f, 255.0f),
            new MessageStyleColorData(63.0f,  126.0f, 191.0f, 255.0f),
            new MessageStyleColorData(63.0f,  191.0f, 143.0f, 255.0f),
            new MessageStyleColorData(191.0f, 159.0f, 63.0f,  255.0f),
        };
        public static readonly uint[] PROPORTIONAL_CHAR_CODES = new uint[144]
        {
            0x3001, 0x3002, 0xFF0C, 0xFF0E,
            0x30FB, 0xFF1F, 0xFF01, 0x309B,
            0x309C, 0xFF40, 0x30FD, 0x30FE,
            0x309D, 0x309E, 0x3003, 0x3005,
            0x3006, 0x2018, 0x2019, 0x201C,
            0x201D, 0xFF08, 0xFF09, 0x3014,
            0x3015, 0xFF3B, 0xFF3D, 0xFF5B,
            0xFF5D, 0x3008, 0x3009, 0x300A,
            0x300B, 0x300C, 0x300D, 0x300E,
            0x300F, 0x3010, 0x3011, 0x00B0,
            0x2032, 0x2033, 0xFFE5, 0xFF04,
            0x00A2, 0x00A3, 0x3012, 0x3041,
            0x3043, 0x3045, 0x3046, 0x3047,
            0x3049, 0x304D, 0x304E, 0x304F,
            0x3050, 0x3053, 0x3054, 0x3055,
            0x3056, 0x3057, 0x3058, 0x3063,
            0x3064, 0x3065, 0x3066, 0x3067,
            0x3068, 0x3069, 0x306B, 0x3072,
            0x3073, 0x3074, 0x307E, 0x308A,
            0x308E, 0x30A1, 0x30A2, 0x30A3,
            0x30A4, 0x30A5, 0x30A7, 0x30A9,
            0x30B3, 0x30B4, 0x30B7, 0x30B8,
            0x30B9, 0x30BA, 0x30BD, 0x30BE,
            0x30C3, 0x30C8, 0x30C9, 0x30CC,
            0x30CE, 0x30D2, 0x30D3, 0x30D4,
            0x30D5, 0x30D6, 0x30D7, 0x30DF,
            0x30E1, 0x30E3, 0x30E5, 0x30E7,
            0x30E8, 0x30EA, 0x30EC, 0x30EE,
            0x30EF, 0x30F2, 0x30F3, 0x30F4,
            0x30F5, 0x30F6, 0xFF21, 0xFF22,
            0xFF23, 0xFF24, 0xFF25, 0xFF26,
            0xFF27, 0xFF28, 0xFF29, 0xFF2A,
            0xFF2B, 0xFF2C, 0xFF2D, 0xFF2E,
            0xFF2F, 0xFF30, 0xFF31, 0xFF32,
            0xFF33, 0xFF34, 0xFF35, 0xFF36,
            0xFF37, 0xFF38, 0xFF39, 0xFF3A,
        };
    }
}