namespace Dpr.Battle.View.Systems
{
	public enum SUBSEQ_POKE_CHANGE_EFFECT : int
	{
		HIDE_TOK_WIN = 0,
		HIDE_TOK_WIN_WAIT = 1,
		MIGAWARI_CHECK = 2,
		MIGAWARI_OUT = 3,
		MIGAWARI_OUT_WAIT = 4,
		MIGAWARI_OUT_UPDATE = 5,
		START_EFFECT = 6,
		UPDATE_EFFECT = 7,
		MIGAWARI_IN = 8,
		MIGAWARI_IN_WAIT = 9,
		MIGAWARI_IN_UPDATE = 10,
		FINISH_WAZA = 11,
	}
}