namespace DPData
{
	internal enum GNSID : int
	{
		GNSID_GLB_SINGLE = 0,
		GNSID_GLB_DOUBLE = 1,
		GNSID_GLB_MULTI = 2,
		GNSID_GLB_CMULTI = 3,
		GNSID_GLB_WIFI = 4,
		GNSID_GLB_WIN = 5,
		GNSID_GLP_KILL = 6,
		GNSID_GLP_CAPUTURE = 7,
		GNSID_GLP_HATCHING = 8,
		GNSID_GLP_FISHING = 9,
		GNSID_GLC_GPX = 10,
		GNSID_GLC_GPXPER = 11,
		GNSID_GLC_RIBBON = 12,
		GNSID_GRB_SINGLE = 13,
		GNSID_GRB_DOUBLE = 14,
		GNSID_GRB_MULTI = 15,
		GNSID_GRB_CMULTI = 16,
		GNSID_GRB_WIFI = 17,
		GNSID_GRB_WIN = 18,
		GNSID_GRP_KILL = 19,
		GNSID_GRP_CAPUTURE = 20,
		GNSID_GRP_HATCHING = 21,
		GNSID_GRP_FISHING = 22,
		GNSID_GRC_GPX = 23,
		GNSID_GRC_GPXPER = 24,
		GNSID_GRC_RIBBON = 25,
	}
}