namespace DPData
{
    public enum INTERVIEWER_DATA_ID_INT : int
    {
        INTERVIEWER_INT_DATA000 = 0,
        INTERVIEWER_INT_DATA001 = 1,
        INTERVIEWER_INT_DATA002 = 2,
        INTERVIEWER_INT_DATA003 = 3,
        INTERVIEWER_INT_DATA004 = 4,
        INTERVIEWER_INT_DATA005 = 5,
        INTERVIEWER_INT_DATA006 = 6,
        INTERVIEWER_INT_DATA007 = 7,
        INTERVIEWER_INT_MAX = 8,
    }
}