namespace DPData
{
    public enum INTERVIEWER_DATA_ID_STR : int
    {
        INTERVIEWER_STR_DATA000 = 0,
        INTERVIEWER_STR_DATA001 = 1,
        INTERVIEWER_STR_DATA002 = 2,
        INTERVIEWER_STR_DATA003 = 3,
        INTERVIEWER_STR_DATA004 = 4,
        INTERVIEWER_STR_DATA005 = 5,
        INTERVIEWER_STR_DATA006 = 6,
        INTERVIEWER_STR_DATA007 = 7,
        INTERVIEWER_STR_DATA008 = 8,
        INTERVIEWER_STR_DATA009 = 9,
        INTERVIEWER_STR_MAX = 10,
    }
}