namespace DPData
{
    public enum RANDOMGROUP : int
    {
        RANDOMGROUP_MINE = 0,
        RANDOMGROUP_MYUSE = 1,
        RANDOMGROUP_DATA0 = 2,
        RANDOMGROUP_DATA1 = 3,
        RANDOMGROUP_DATA2 = 4,
        RANDOMGROUP_DATA3 = 5,
        RANDOMGROUP_DATA4 = 6,
        RANDOMGROUP_DATA5 = 7,
        RANDOMGROUP_DATA6 = 8,
        RANDOMGROUP_DATA7 = 9,
        RANDOMGROUP_DATA8 = 10,
        RANDOMGROUP_DATA9 = 11,
        RANDOMGROUP_MAX = 12,
    }
}