namespace DPData
{
    public enum TV_DATA_ID_INT_DEF : int
    {
        BattleTowerWinCount = 0,
        YourPokemonMonsNo = 1,
        FavoritePoketch = 2,
        ContestName = 3,
        ContestRankName = 4,
        ContestRankingNumber = 5,
        Poffin = 6,
        BallDecorationTrainer = 7,
        PokemonCaptureMonsNo = 8,
        PokemonCaptureBall = 9,
        PokemonCaptureBallCount = 10,
        PokemonCaptureFailedBallCount = 11,
        FishingItem = 12,
        FishingMonsNo = 13,
        HiddenItemNo = 14,
        EggHatchPlace = 15,
        ChangeNicknameMonsNo = 16,
        KasekiHoriItem = 17,
        SafariMonsNo = 18,
        SafariMonsCount = 19,
        KanpouItemNo = 20,
        KinomiId = 21,
        KinomiCount = 22,
        CustomBallSealName = 23,
        CustomBallMonsNo = 24,
        Monohiroi = 25,
        HimitsukichiReceiveNice = 26,
        HimitsukichiSendNice = 27,
        BattleTowerRecordUpdateMonsNo = 28,
        BattleTowerRecordUpdateWinCount = 29,
        PokemonSizeRecordUpdateMonsNo = 30,
        PokemonSizeRecordUpdateSizeValue = 31,
        PokemonSizeRecordUpdate_Dummy = 32,
        KinomiMasterKinomiId = 33,
        SafariMasterPokemonCount = 34,
        StatueMasterStatueCount = 35,
        HikariIshiCount = 36,
        GroupPokemonType = 37,
        WeatherPlace = 38,
        TairyouHasseiPlace = 39,
        TairyouHasseiMonsNo = 40,
        CompatibilityPokemonType = 41,
        CompatibilityEffectivePokemonType = 42,
        KinomiInformationPlace = 43,
        WildPokemonItemMonsNo = 44,
        WildPokemonItemItemNo = 45,
        FashionStyle = 46,
        FashionPlace = 47,
        HiddenPlaceNo = 48,
        Max = 49,
    }
}