namespace DPData
{
    public enum TV_DATA_ID_STR_DEF : int
    {
        BattleTowerPlayerName = 0,
        YourPokemonPlayerName = 1,
        YourPokemonPokemonName = 2,
        FavoritePoketchPlayerName = 3,
        ContestPokemonName = 4,
        ContestPlayerName = 5,
        PersonalityPlayerName = 6,
        PoffinPlayerName = 7,
        TsureArukiPlayerName = 8,
        TsureArukiPokemonName = 9,
        PokemonCapturePlayerName = 10,
        PokemonCapturePokemonName = 11,
        PokemonCaptureFailedPlayerName = 12,
        FishingPlayerName = 13,
        GroupChangePlayerName = 14,
        GroupChangeGroupName = 15,
        HiddenItemPlayerName = 16,
        EggHatchPlayerName = 17,
        EggHatchPokemonName = 18,
        ChangeNicknamePlayerName = 19,
        ChangeNicknamePokemonName = 20,
        KasekiHoriPlayerName = 21,
        SafariPlayerName = 22,
        KanpouPlayerName = 23,
        KanpouPokemonName = 24,
        KinomiPlayerName = 25,
        NewGroupPlayerName = 26,
        NewGroupGroupName = 27,
        CustomBallPlayerName = 28,
        MonohiroiPlayerName = 29,
        MonohiroiPokemonName = 30,
        HimitsukichiReceiveNicePlayerName = 31,
        HimitsukichiSendNicePlayerName = 32,
        BattleTowerRecordUpdatePlayerName = 33,
        PokemonSizeRecordUpdatePlayerName = 34,
        KinomiMasterKinomiPlayerName = 35,
        SafariMasterPlayerName = 36,
        StatueMasterPlayerName = 37,
        HikariIshiPlayerName = 38,
        GroupMemberName = 39,
        GroupGroupName = 40,
        FashionPlayerName = 41,
    }
}