namespace Dpr.SequenceEditor
{
	public enum SEQ_STENCIL_TARGET : int
	{
		SEQ_STENCIL_TARGET_NONE = 0,
		SEQ_STENCIL_TARGET_POKEMON = 1,
		SEQ_STENCIL_TARGET_TRAINER = 2,
		SEQ_STENCIL_TARGET_EFFECTMODEL = 3,
		SEQ_STENCIL_TARGET_PARTICLE = 4,
	}
}