namespace Dpr.SequenceEditor
{
	public enum SEQ_DEF_MASK_TEX_PATTERN : int
	{
		SEQ_DEF_MASK_TEX_PATTERN_1 = 0,
		SEQ_DEF_MASK_TEX_PATTERN_2 = 1,
		SEQ_DEF_MASK_TEX_PATTERN_3 = 2,
		SEQ_DEF_MASK_TEX_PATTERN_4 = 3,
		SEQ_DEF_MASK_TEX_PATTERN_5 = 4,
		SEQ_DEF_MASK_TEX_PATTERN_6 = 5,
		SEQ_DEF_MASK_TEX_PATTERN_7 = 6,
		SEQ_DEF_MASK_TEX_PATTERN_8 = 7,
		SEQ_DEF_MASK_TEX_PATTERN_9 = 8,
		SEQ_DEF_MASK_TEX_PATTERN_10 = 9,
	}
}