namespace Dpr.SequenceEditor
{
	public enum SEQ_DEF_FAIRY_QUIZ_TYPE : int
	{
		SEQ_DEF_FAIRY_QUIZ_TYPE_NONE = 0,
		SEQ_DEF_FAIRY_QUIZ_TYPE_ATTACK = 1,
		SEQ_DEF_FAIRY_QUIZ_TYPE_ATTACK2 = 2,
		SEQ_DEF_FAIRY_QUIZ_TYPE_DEFENSE = 3,
		SEQ_DEF_FAIRY_QUIZ_TYPE_DEFENSE2 = 4,
		SEQ_DEF_FAIRY_QUIZ_TYPE_AGILITY = 5,
		SEQ_DEF_FAIRY_QUIZ_TYPE_AGILITY2 = 6,
	}
}