namespace Dpr.SequenceEditor
{
	public enum SEQ_DEF_TRAINER_MOTION : int
	{
		SEQ_DEF_TRAINER_MOTION_ADVENT02_B = 0,
		SEQ_DEF_TRAINER_MOTION_ADVENT_B = 1,
		SEQ_DEF_TRAINER_MOTION_WAIT_B = 2,
		SEQ_DEF_TRAINER_MOTION_WAIT02_B = 3,
		SEQ_DEF_TRAINER_MOTION_ORDER_B = 4,
		SEQ_DEF_TRAINER_MOTION_LOSE01_B = 5,
		SEQ_DEF_TRAINER_MOTION_SPEAK01_B = 6,
		SEQ_DEF_TRAINER_MOTION_WIN01_B = 7,
		SEQ_DEF_TRAINER_MOTION_SPEAK02_B = 8,
		SEQ_DEF_TRAINER_MOTION_WALK_B = 9,
		SEQ_DEF_TRAINER_MOTION_RUN_B = 10,
		SEQ_DEF_TRAINER_MOTION_ADVENT03_B = 11,
		SEQ_DEF_TRAINER_MOTION_ADVENT04_B = 12,
		SEQ_DEF_TRAINER_MOTION_ADVENT05_B = 13,
		SEQ_DEF_TRAINER_MOTION_ADVENT06_B = 14,
		SEQ_DEF_TRAINER_MOTION_ADVENT07_B = 15,
	}
}