namespace Dpr.SequenceEditor
{
	public enum SEQ_DEF_WEATHER : int
	{
		SEQ_DEF_WEATHER_NONE = 0,
		SEQ_DEF_WEATHER_SHINE = 1,
		SEQ_DEF_WEATHER_RAIN = 2,
		SEQ_DEF_WEATHER_SNOW = 3,
		SEQ_DEF_WEATHER_SAND = 4,
		SEQ_DEF_WEATHER_STORM = 5,
		SEQ_DEF_WEATHER_DAY = 6,
		SEQ_DEF_WEATHER_TURBULENCE = 7,
	}
}