namespace Dpr.SequenceEditor
{
	public enum SEQ_DEF_LG_SHAPE : int
	{
		SEQ_DEF_LG_SHAPE_DISABLE = 0,
		SEQ_DEF_LG_SHAPE_TYPE_A0 = 1,
		SEQ_DEF_LG_SHAPE_TYPE_A1 = 2,
		SEQ_DEF_LG_SHAPE_TYPE_A2 = 3,
		SEQ_DEF_LG_SHAPE_TYPE_A3 = 4,
		SEQ_DEF_LG_SHAPE_TYPE_B0 = 5,
		SEQ_DEF_LG_SHAPE_TYPE_B1 = 6,
		SEQ_DEF_LG_SHAPE_TYPE_B2 = 7,
		SEQ_DEF_LG_SHAPE_TYPE_B3 = 8,
		SEQ_DEF_LG_SHAPE_TYPE_C0 = 9,
		SEQ_DEF_LG_SHAPE_TYPE_C1 = 10,
		SEQ_DEF_LG_SHAPE_TYPE_C2 = 11,
		SEQ_DEF_LG_SHAPE_TYPE_C3 = 12,
		SEQ_DEF_LG_SHAPE_TYPE_D0 = 13,
		SEQ_DEF_LG_SHAPE_TYPE_D1 = 14,
		SEQ_DEF_LG_SHAPE_TYPE_D2 = 15,
		SEQ_DEF_LG_SHAPE_TYPE_D3 = 16,
		SEQ_DEF_LG_SHAPE_TYPE_E0 = 17,
		SEQ_DEF_LG_SHAPE_TYPE_E1 = 18,
		SEQ_DEF_LG_SHAPE_TYPE_E2 = 19,
		SEQ_DEF_LG_SHAPE_TYPE_E3 = 20,
	}
}