public enum FLOOR_DISPLAY : int
{
	FIRST_FLOOR = 0,
	SECOND_FLOOR = 1,
	THAAD_FLOOR = 2,
	FOURTH_FLOOR = 3,
	FIFTH_FLOOR = 4,
	FIRST_BASEMENT_FLOOR = 5,
	SECOND_BASEMENT_FLOOR = 6,
	OBSERVATORY = 7,
}