public enum SYS_WEATHER : int
{
    SUNNY = 0,
    CLOUDINESS = 1,
    RAIN = 2,
    STRAIN = 3,
    SPARK = 4,
    SNOW = 5,
    SNOWSTORM = 6,
    SNOWSTORM_H = 7,
    FOG = 8,
    VOLCANO = 9,
    SANDSTORM = 10,
    DIAMONDDUST = 11,
    SPIRIT = 12,
    MYSTIC = 13,
    MIST1 = 14,
    MIST2 = 15,
    FLASH = 16,
    SPARK_EFF = 17,
    FOGS = 18,
    FOGM = 19,
    MAX = 20,
}