public enum WallpaperID : int
{
    FOREST = 0,
    CITY = 1,
    DESERT = 2,
    SAVANNA = 3,
    CRAG = 4,
    VOLCANO = 5,
    SNOW = 6,
    CAVE = 7,
    BEACH = 8,
    SEAFLOOR = 9,
    RIVER = 10,
    SKY = 11,
    POKÉMON_CENTER = 12,
    MACHINE = 13,
    CHECKS = 14,
    SIMPLE = 15,
    SPACE = 16,
    BACKYARD = 17,
    NOSTALGIC = 18,
    TORCHIC = 19,
    TRIO = 20,
    PIKAPIKA = 21,
    LEGEND = 22,
    TEAM_GALACTIC = 23,
    DISTORTION_PT = 24,
    TRIO_PT = 25,
    CONTEST_PT = 26,
    PIKAPIKA_PT = 27,
    NOSTALGIC_PT = 28,
    LEGEND_PT = 29,
    CROAGUNK_PT = 30,
    TEAMGALACTIC_PT = 31,
}