namespace Dpr.GMS
{
	public enum MessageID : int
	{
		FinishGMS = 0,
		AnnounceTrade = 1,
		ConfirmStartTrade = 2,
		ConfirmReplacePoke = 3,
		CompleteSetNewPoke = 4,
		CancelReplacePoke = 5,
		ConfirmDeleteMark = 6,
		CompleteDeleteMark = 7,
		ConfirmChangePoke = 8,
		CompleteChangePoke = 9,
		WaitConnect = 10,
		CancelTrade = 11,
		Timeout = 12,
		FoundTradeTarget = 13,
		SelectReplaceData = 14,
		ConfirmStayData = 15,
		CompleteReplacePoke = 16,
		TradeDate = 17,
		YES = 18,
		NO = 19,
		DecideTrade = 20,
		LookEarth = 21,
		Cancel = 22,
		Delete = 23,
		Mark = 24,
		ContinueTrade = 25,
		Reward = 26,
		StartReport = 27,
		CompletedReport = 28,
		DisconnectServer = 29,
		InvalidMyMons = 30,
		InvalidFriendMons = 31,
		DisconnectPenalty = 32,
		ConfirmDeleteRecord = 33,
		CompleteDeleteRecord = 34,
	}
}