namespace Dpr.Battle.View
{
    public enum BattleSetupIntroID : int
    {
        THROW_PLAYER_SINGLE = 0,
        THROW_PLAYER_SINGLE_FAST = 1,
        THROW_PLAYER_DOUBLE_EXIST_FRIEND = 2,
        THROW_PLAYER_DOUBLE_NOT_EXIST_FRIEND = 3,
        THROW_ENEMY_SINGLE = 4,
        THROW_ENEMY_SINGLE_COMM = 5,
        THROW_ENEMY_DOUBLE_IS_MULTI = 6,
        THROW_ENEMY_DOUBLE_IS_MULTI_COMM = 7,
        THROW_ENEMY_DOUBLE = 8,
        THROW_ENEMY_DOUBLE_COMM = 9,
        THROW_PLAYER_SINGLE_TUREARUKI = 10,
        THROW_PLAYER_SINGLE_HAPPY_A = 11,
        THROW_PLAYER_SINGLE_HAPPY_B = 12,
        THROW_PLAYER_SINGLE_HAPPY_C = 13,
        THROW_PLAYER_SINGLE_HATE = 14,
        THROW_ENEMY_SINGLE_HEROINE = 15,
    }
}