namespace poketool.pokeplace
{
	public enum MapName : int
	{
		MAPNAME_SODATEYA = 0,
		MAPNAME_NAIBUTUUSINKOUKAN = 1,
		MAPNAME_TUUSINKOUKAN = 2,
		MAPNAME_KANTO = 3,
		MAPNAME_ZYOTO = 4,
		MAPNAME_HOUEN = 5,
		MAPNAME_SINOU = 6,
		MAPNAME_HUSEI = 7,
		MAPNAME_TOOKUHANARETATOTI = 8,
		MAPNAME_TABINOOZISAN = 9,
		MAPNAME_GEN = 10,
	}
}