namespace Pml.PokePara
{
	public enum Memories : int
	{
		EGG_TAKEN_YEAR = 0,
		EGG_TAKEN_MONTH = 1,
		EGG_TAKEN_DAY = 2,
		EGG_TAKEN_PLACE = 3,
		FIRST_CONTACT_YEAR = 4,
		FIRST_CONTACT_MONTH = 5,
		FIRST_CONTACT_DAY = 6,
		FIRST_CONTACT_PLACE = 7,
		CAPTURED_BALL = 8,
		CAPTURED_LEVEL = 9,
		LEVEL_WITH_PARENT = 10,
		CODE_WITH_PARENT = 11,
		DATA_WITH_PARENT = 12,
		FEEL_WITH_PARENT = 13,
		LEVEL_WITH_OTHERS = 14,
		CODE_WITH_OTHERS = 15,
		DATA_WITH_OTHERS = 16,
		FEEL_WITH_OTHERS = 17,
	}
}