namespace Dpr.NetworkUtils
{
	public enum SessionErrorType : int
	{
		InternetGo_DONOT_LOGIN_CALL_MISS = 0,
		InternetGo_DONOT_NEXUID_CALL_MISS = 1,
		InternetGo_Error = 2,
		InternetGo_DoNotInet = 3,
		InternetGo_DoNotNSO = 4,
		InternetGo_DoNotGetNexUID = 5,
		InternetGo_DoNotGetNSAID = 6,
		InternetGo_DoNotLogin = 7,
		InternetGo_Crash = 8,
		Failed_NetworkInitAsync = 9,
		Failed_SessionCreateAsync = 10,
		Failed_SessionJoinAsync = 11,
		Failed_SessionRandomAsync = 12,
		Failed_SettingSet = 13,
		Failed_SessionRestartRequestAsync = 14,
		Failed_CheckRequestAutoAsync = 15,
		Session_NotFind = 16,
		Cannot_CallStartSession = 17,
		DoNot_StateWait = 18,
		GamingError_InPolling = 19,
		Crash_InPolling = 20,
		DoNot_FindSessionIndex = 21,
		SendPacket_NotSessionInitialized = 22,
		SendPacket_AloneSession = 23,
		SendPacket_InvalidIlcaNetPacketType = 24,
		SendPacket_PacketWriterReNotUseUn = 25,
		SendPacket_SendSocketResultFailure = 26,
		SendPacket_SendSocketBufferFull = 27,
		SendPacket_InvalidStationIndex = 28,
		SendPacket_SessionInfoFuncFailure = 29,
		SendPacket_SendToSelf = 30,
		SendPacket_RecvCrash = 31,
		SendPacket_RecvSocketResultFailure = 32,
		SendPacket_NetGamerIsNotActive = 33,
		SendPacket_NetGamerIsNotHomeGamer = 34,
		Validate_RequestResultFailed = 35,
		Validate_CallDifferentRequest = 36,
		Validate_FailedGetPublicKey = 37,
		Validate_FailedGetIllegalData = 38,
		Validate_FindIllegalData = 39,
		Failed_NotPerformValidate = 40,
		Failed_CallGMStationTrade = 41,
		Sercretbase_FailedCallIineGetAsync = 42,
		Sercretbase_FailedGetGoodCount = 43,
		Sercretbase_FailedCallIineSetAsync = 44,
		Sercretbase_FailedSendGood = 45,
		Error_NotFoundErrorCode = 46,
		Warning = 47,
		None = 48,
	}
}