namespace Dpr.Battle.Logic
{
	public enum BtlAiscriptBit : uint
	{
		BTL_AISCRIPT_BIT_WAZA_BASIC = 1,
		BTL_AISCRIPT_BIT_WAZA_STRONG = 2,
		BTL_AISCRIPT_BIT_WAZA_EXPERT = 4,
		BTL_AISCRIPT_BIT_WAZA_DOUBLE = 8,
		BTL_AISCRIPT_BIT_WAZA_ALLOWANCE = 16,
		BTL_AISCRIPT_BIT_ITEM_BASIC = 32,
		BTL_AISCRIPT_BIT_POKECHANGE_BASIC = 64,
	}
}