namespace Dpr.Battle.Logic
{
	public enum CheerEffect : int
	{
		CHEER_EFFECT_NONE = 0,
		CHEER_EFFECT_RECOVER_HP = 1,
		CHEER_EFFECT_CURE_SICK = 2,
		CHEER_EFFECT_RANKUP = 3,
		CHEER_EFFECT_REFLECTOR = 4,
		CHEER_EFFECT_HIKARINOKABE = 5,
		CHEER_EFFECT_BREAK_GWALL = 6,
		CHEER_EFFECT_NUM = 7,
	}
}